const I={
 dash:['⌂','לוח בקרה'], radar:['◎','Radar'], candidates:['⌕','מועמדי CT.gov'], resolved:['✓','אירועים שנפתרו'], paper:['◇','Paper Signals'], validation:['▥','Validation'], system:['⚙','מערכת']
};
const HE={
 cls:{REVIEW:'לבדיקה',WATCH:'מעקב',AVOID_BINARY:'להימנע מבינארי',QUARANTINED:'בהסגר אימות',STALE_UNRESOLVED:'חלון חלף',HOLD_THROUGH_CANDIDATE:'HOLD מאומת',RUNUP_CANDIDATE:'RUN-UP מאומת',RESOLVED:'נפתר'},
 state:{SCHEDULED:'מתוזמן',VERIFIED:'מאומת',DISCOVERED:'נמצא',QUARANTINED:'הסגר',APPROVED:'אושר',CRL:'CRL',DELAYED:'נדחה',CANCELLED:'בוטל',RESOLVED:'נפתר'},
 type:{P3_TOPLINE:'Phase 3',P2_TOPLINE:'Phase 2',P12_DATA:'Phase 1/2',INTERIM:'Interim',PDUFA_NME:'PDUFA',PDUFA_SUPP:'PDUFA sNDA',PDUFA_GENERIC:'PDUFA',ADCOM:'AdCom',FILING:'הגשה',CONFERENCE:'כנס'}
};
let D=null, page='dash', apiMode=false, search='', radarFilters={type:'',cls:'',verify:''};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtN=n=>new Intl.NumberFormat('he-IL').format(n??0); const pct=x=>x==null?'—':`${(x*100).toFixed(1)}%`;
function badge(text,kind='slate'){return `<span class="badge ${kind}">${esc(text)}</span>`}
function clsBadge(c){let k=c==='AVOID_BINARY'||c==='QUARANTINED'?'red':c==='REVIEW'?'blue':c==='HOLD_THROUGH_CANDIDATE'||c==='RUNUP_CANDIDATE'?'green':c==='WATCH'?'amber':'slate';return badge(HE.cls[c]||c,k)}
function stateBadge(s){let k=['SCHEDULED','VERIFIED','APPROVED'].includes(s)?'green':s==='QUARANTINED'||s==='CRL'?'red':s==='DELAYED'?'amber':'slate';return badge(HE.state[s]||s,k)}
function typeBadge(t){return badge(HE.type[t]||t,t?.startsWith('PDUFA')?'purple':t==='P3_TOPLINE'?'blue':'slate')}
function score(v){if(v==null)return '—';let k=v>=75?'green':v<45?'red':v<60?'amber':'';return `<div class="score"><strong>${v}</strong><span class="track"><span class="fill ${k}" style="width:${Math.min(100,Math.max(0,v))}%"></span></span></div>`}
function win(a){let w=a?.date?.window;if(!w)return '—';return `<span class="ltr nowrap">${esc(w.start)}${w.end&&w.end!==w.start?' → '+esc(w.end):''}</span>`}
function days(a){let d=a.days_to;if(d==null)return '—'; if(d<0)return `בחלון / עבר ${Math.abs(d)} יום`; if(d===0)return 'היום'; return `עוד ${d} ימים`}
function queryText(a){return [a.ticker,a.company,a.program,a.indication,a.type,a.phase].join(' ').toLowerCase()}
function filteredLive(){let rows=D?.live||[];let q=search.trim().toLowerCase();return rows.filter(a=>(!q||queryText(a).includes(q))&&(!radarFilters.type||a.type===radarFilters.type)&&(!radarFilters.cls||a.classification?.class===radarFilters.cls)&&(!radarFilters.verify||a.state?.verification_state===radarFilters.verify))}
function setLoading(v){$('loading').classList.toggle('on',!!v)}
function toast(msg){let t=$('toast');t.textContent=msg;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2600)}
function renderMenu(){ $('menu').innerHTML=Object.entries(I).map(([k,[ico,label]])=>`<button data-page="${k}" class="${page===k?'active':''}"><span class="ico">${ico}</span>${label}</button>`).join(''); $('menu').querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;$('sidebar').classList.remove('open');render();}); }
function sideFoot(){if(!D)return;let r=D.validation.runup,h=D.validation.hold_through;$('sideFoot').innerHTML=`<div>גרסה <b>${esc(D.version)}</b></div><div class="gate-mini"><span><i class="gate-dot ${r.satisfied?'open':''}"></i>RUN-UP</span><b>${r.n}/${r.min_n}</b><span><i class="gate-dot ${h.satisfied?'open':''}"></i>HOLD</span><b>${h.n}/${h.min_n}</b></div>`}
function pageTitle(title,sub,extra=''){return `<div class="page-title"><div><h2>${title}</h2><p>${sub}</p></div><div class="meta-line">${extra}</div></div>`}
function metric(label,value,sub='',accent=false){return `<div class="metric ${accent?'accent':''}"><div class="label">${label}</div><div class="value">${value}</div><div class="sub">${sub}</div></div>`}
function radarTable(rows,limit=null){let rr=limit?rows.slice(0,limit):rows;if(!rr.length)return `<div class="empty">לא נמצאו אירועים התואמים למסננים.</div>`;return `<div class="table-wrap"><table><thead><tr><th>טיקר / חברה</th><th>תוכנית / התוויה</th><th>סוג</th><th>חלון</th><th>אימות</th><th>Impact</th><th>Evidence</th><th>סיווג</th></tr></thead><tbody>${rr.map(a=>`<tr class="clickable" data-event="${esc(a.id)}"><td><span class="ticker">${esc(a.ticker||'—')}</span><div class="company">${esc(a.company||'')}</div></td><td class="program"><b>${esc(a.program||'')}</b><div class="company">${esc(a.indication||'')}${a.phase?' · '+esc(a.phase):''}</div></td><td>${typeBadge(a.type)}</td><td>${win(a)}<div class="company">${days(a)}</div></td><td>${stateBadge(a.state?.status)}<div class="company">${esc(a.state?.verification_confidence??0)}% · ${esc(a.state?.verification_state||'')}</div></td><td>${score(a.impact?.score)}</td><td>${score(a.evidence?.score)}<div class="company">${esc(a.evidence?.category||'')}</div></td><td>${clsBadge(a.classification?.class)}</td></tr>`).join('')}</tbody></table></div>`}
function topRank(){let arr=[...(D.live||[])].sort((a,b)=>(b.impact?.score||0)-(a.impact?.score||0)).slice(0,6);return `<div class="rank-list">${arr.map((a,i)=>`<div class="rank-item" data-event="${esc(a.id)}"><div class="rank-num">${i+1}</div><div class="main"><b><span class="ltr">${esc(a.ticker)}</span> · ${esc(a.program)}</b><div class="company">${esc(HE.type[a.type]||a.type)} · ${days(a)}</div></div><div class="right">${score(a.impact.score)}</div></div>`).join('')}</div>`}
function dashboard(){let s=D.summary;return pageTitle('לוח בקרה','תמונת המצב של ה־Catalyst Radar',`נכון ל־${esc(D.today)} · נוצר ${esc(D.generated_at?.replace('T',' ').slice(0,16))}`)+`<div class="notice blue-note"><b>עיקרון עבודה:</b> Impact גבוה אומר שהאירוע עשוי להזיז את המניה — לא שהוא חיובי. HOLD/RUN-UP נשארים נעולים עד להוכחת edge מחוץ למדגם.</div><div class="cards">${metric('אירועים פתוחים',s.live_events,'Verified + Review',true)}${metric('מאומתים',s.verified,'מקור ראשוני')}${metric('≤30 ימים',s.next_30_days,'אירועים קרובים')}${metric('Impact ≥70',s.high_impact,'אירועים מהותיים')}${metric('בהסגר',s.quarantined,'דורשים אימות')}${metric('Paper Signals',s.paper_signals,'Forward test')}</div><div class="two-col"><section class="panel"><div class="panel-head"><h3>האירועים החשובים כרגע</h3><span class="spacer"></span><button class="btn" onclick="page='radar';render()">לכל ה־Radar</button></div>${radarTable([...(D.live||[])].sort((a,b)=>(b.impact?.score||0)-(a.impact?.score||0)),7)}</section><section class="panel"><div class="panel-head"><h3>Impact Ranking</h3></div><div class="panel-body">${topRank()}</div></section></div><div class="three-col"><div class="gate">${gateBlock('RUN-UP',D.validation.runup)}</div><div class="gate">${gateBlock('HOLD THROUGH',D.validation.hold_through)}</div><div class="gate"><div class="gate-top"><h4>Discovery Queue</h4>${badge(fmtN(s.candidates),'blue')}</div><div class="progress"><span style="width:${s.candidates?Math.min(100,100*s.mapped_candidates/s.candidates):0}%"></span></div><small>${fmtN(s.mapped_candidates)} מועמדים ממופים לטיקר מתוך ${fmtN(s.candidates)}</small></div></div>`}
function gateBlock(name,g){let p=Math.min(100,100*(g.n||0)/(g.min_n||1));return `<div class="gate-top"><h4>${name}</h4>${badge(g.satisfied?'OPEN':'LOCKED',g.satisfied?'green':'red')}</div><div class="progress"><span style="width:${p}%"></span></div><small>${g.n}/${g.min_n} · ${esc(g.note||'')}</small>`}
function radar(){let rows=filteredLive();let types=[...new Set((D.live||[]).map(x=>x.type))].sort();let classes=[...new Set((D.live||[]).map(x=>x.classification?.class))].filter(Boolean).sort();return pageTitle('Catalyst Radar','אירועים שעברו discovery ואימות ברמות שונות',`${rows.length} מתוך ${D.live.length}`)+`<div class="notice">אירוע עם מקור משני בלבד נשאר <b>QUARANTINED</b>. CT.gov משמש לגילוי בלבד ואינו תאריך readout.</div><section class="panel"><div class="panel-body"><div class="filters"><select id="fType"><option value="">כל הסוגים</option>${types.map(x=>`<option value="${esc(x)}" ${radarFilters.type===x?'selected':''}>${esc(HE.type[x]||x)}</option>`).join('')}</select><select id="fClass"><option value="">כל הסיווגים</option>${classes.map(x=>`<option value="${esc(x)}" ${radarFilters.cls===x?'selected':''}>${esc(HE.cls[x]||x)}</option>`).join('')}</select><select id="fVerify"><option value="">כל רמות האימות</option><option value="VERIFIED" ${radarFilters.verify==='VERIFIED'?'selected':''}>VERIFIED</option><option value="QUARANTINED" ${radarFilters.verify==='QUARANTINED'?'selected':''}>QUARANTINED</option></select><span class="count">${rows.length} אירועים</span></div>${radarTable(rows)}</div></section>`}
function candidates(){let rows=(D.candidates||[]).filter(c=>!search||[c.nct_id,c.sponsor,c.ticker,c.title,c.phase].join(' ').toLowerCase().includes(search.toLowerCase()));return pageTitle('מועמדי ClinicalTrials.gov','Discovery queue — לא אירועים מאומתים',`${rows.length} מועמדים`)+`<div class="notice"><b>חשוב:</b> Primary Completion Date הוא estimate של sponsor. המועמד הופך ל־Catalyst רק לאחר אימות מול SEC/FDA/IR.</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>NCT</th><th>Sponsor</th><th>טיקר</th><th>שלב</th><th>מחקר</th><th>Primary completion</th><th>עודכן</th><th>סטטוס</th></tr></thead><tbody>${rows.map(c=>`<tr><td><span class="ltr">${esc(c.nct_id)}</span></td><td>${esc(c.sponsor)}</td><td><span class="ticker">${esc(c.ticker||'—')}</span>${c.ticker?`<div class="company">confidence ${Math.round((c.ticker_confidence||0)*100)}%</div>`:''}</td><td>${esc(c.phase||'')}</td><td class="program">${esc(c.title)}</td><td><span class="ltr">${esc(c.primary_completion||'—')}</span></td><td><span class="ltr">${esc(c.last_update_posted||'—')}</span></td><td>${c.promoted_event_id?badge('קודם לאירוע','green'):badge('Discovery only','amber')}</td></tr>`).join('')}</tbody></table></div></section>`}
function resolved(){let rows=D.resolved||[];return pageTitle('אירועים שנפתרו','אירועים שהוסרו מה־Radar הפעיל לאחר Resolution',`${rows.length} אירועים`)+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>טיקר</th><th>תוכנית</th><th>סוג</th><th>סטטוס</th><th>נפתר</th><th>הערה</th></tr></thead><tbody>${rows.map(a=>`<tr><td><span class="ticker">${esc(a.ticker)}</span><div class="company">${esc(a.company||'')}</div></td><td class="program">${esc(a.program)}</td><td>${typeBadge(a.type)}</td><td>${stateBadge(a.state?.status)}</td><td><span class="ltr">${esc(a.state?.resolved_at||'—')}</span></td><td>${esc(a.state?.note||'')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">עדיין אין אירועים שנפתרו.</td></tr>'}</tbody></table></div></section>`}
function paper(){let rows=D.paper||[];return pageTitle('Paper Signals','Forward-test בלתי ניתן לשכתוב לאחר יצירה',`${rows.length} signals`)+`<div class="notice blue-note">Paper Signal שומר את הניתוח והסיווג כפי שנראו באותו רגע. הוא מיועד לכיול עתידי — לא לביצוע עסקה אוטומטי.</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>אירוע</th><th>נוצר</th><th>חלון</th><th>סיווג</th><th>מחיר</th><th>תוצאה</th><th>Move</th></tr></thead><tbody>${rows.map(r=>`<tr><td><span class="ltr">${esc(r.event_id)}</span></td><td><span class="ltr">${esc(r.created_at)}</span></td><td><span class="ltr">${esc(r.window_start||'—')}</span></td><td>${clsBadge(r.classification)}</td><td>${r.price??'—'}</td><td>${esc(r.clinical||'—')}</td><td>${r.move==null?'—':pct(r.move)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">עדיין אין Paper Signals. פתח אירוע ב־Radar ושמור אותו.</td></tr>'}</tbody></table></div></section>`}
function validation(){let b=D.backtest||{},a=D.historical_audit||{},cov=b.coverage||{};return pageTitle('Validation / Backtest','המערכת לא פותחת מסחר עד שהנתונים עומדים בשערי איכות ו־OOS',`Dataset audit`)+`<div class="three-col"><div class="gate">${gateBlock('RUN-UP',D.validation.runup)}</div><div class="gate">${gateBlock('HOLD THROUGH',D.validation.hold_through)}</div><div class="gate"><div class="gate-top"><h4>Historical Audit</h4>${badge(fmtN(a.eligible||0)+' eligible',a.eligible?'green':'red')}</div><div class="progress"><span style="width:${a.total?Math.min(100,100*(a.eligible||0)/a.total):0}%"></span></div><small>${fmtN(a.eligible||0)} מתוך ${fmtN(a.total||cov.historical_events||0)} עומדים בתנאי האיכות</small></div></div><section class="panel" style="margin-top:18px"><div class="panel-head"><h3>כיסוי היסטורי</h3></div><div class="panel-body"><div class="cards">${metric('Historical events',cov.historical_events??0)}${metric('Pre-event prices',cov.with_pre_event_prices??0)}${metric('Session-aware move',cov.with_session_aware_event_move??0)}${metric('Audit eligible',a.eligible??0)}</div>${(b.warnings||[]).map(x=>`<div class="notice red-note">${esc(x)}</div>`).join('')}</div></section>`}
function system(){let r=D.refresh,w=D.watch_universe||[];return pageTitle('מערכת ומקורות','מצב Pipeline, Universe ו־API',apiMode?'LIVE API':'STATIC SNAPSHOT')+`<div class="three-col"><div class="panel"><div class="panel-head"><h3>מצב נתונים</h3></div><div class="panel-body"><div class="kv"><span class="k">מצב ממשק</span><b>${apiMode?'API חי':'קובץ סטטי'}</b></div><div class="kv"><span class="k">גרסה</span><span class="code">${esc(D.version)}</span></div><div class="kv"><span class="k">Generated</span><span class="ltr">${esc(D.generated_at)}</span></div><div class="kv"><span class="k">Refresh אחרון</span><span>${r?`${esc(r.status)} · ${esc(r.finished_at||r.started_at)}`:'לא בוצע'}</span></div></div></div><div class="panel"><div class="panel-head"><h3>עקרונות מוגנים</h3></div><div class="panel-body">${Object.entries(D.principles||{}).map(([k,v])=>`<div class="kv"><span class="k code">${esc(k)}</span>${v?badge('ON','green'):badge('OFF','red')}</div>`).join('')}</div></div><div class="panel"><div class="panel-head"><h3>פעולות</h3></div><div class="panel-body"><button class="btn primary" ${apiMode?'':'disabled'} onclick="refreshNow()">הרץ Discovery + Verification</button><p class="company">רענון SEC דורש SEC_USER_AGENT תקין. במצב static הפעולה אינה זמינה.</p></div></div></div><section class="panel"><div class="panel-head"><h3>Watch Universe</h3><span class="spacer"></span><span class="company">${w.length} tickers</span></div><div class="table-wrap"><table><thead><tr><th>טיקר</th><th>חברה</th><th>CIK</th><th>מקור</th><th>עודכן</th></tr></thead><tbody>${w.map(x=>`<tr><td><span class="ticker">${esc(x.ticker)}</span></td><td>${esc(x.company||'')}</td><td><span class="ltr">${esc(x.cik||'—')}</span></td><td>${esc(x.source)}</td><td><span class="ltr">${esc(x.updated_at)}</span></td></tr>`).join('')}</tbody></table></div></section>`}
function render(){renderMenu();sideFoot();let html=page==='dash'?dashboard():page==='radar'?radar():page==='candidates'?candidates():page==='resolved'?resolved():page==='paper'?paper():page==='validation'?validation():system();$('main').innerHTML=html;bindRows();if(page==='radar'){['fType','fClass','fVerify'].forEach(id=>{let e=$(id);if(e)e.onchange=()=>{radarFilters[id==='fType'?'type':id==='fClass'?'cls':'verify']=e.value;render();};});}}
function bindRows(){document.querySelectorAll('[data-event]').forEach(x=>x.onclick=()=>openEvent(x.dataset.event));}
function findEvent(id){return (D.live||[]).find(x=>x.id===id)}
function reasonRows(a){return (a.evidence?.reasons||[]).map(r=>`<div class="reason"><span class="delta ${r.delta>0?'good':r.delta<0?'danger':''}">${r.delta>0?'+':''}${r.delta??0}</span><span>${esc(r.text)}</span></div>`).join('')||'<div class="empty">אין פירוט.</div>'}
function risks(a){return (a.risk_flags||[]).map(r=>`<div class="risk ${esc(r.sev)}"><b>${esc(r.sev?.toUpperCase())}</b> · ${esc(r.text)}</div>`).join('')||'<div class="company">לא זוהו דגלי סיכון מובנים.</div>'}
function sources(a){return (a.sources||[]).map(s=>`<div class="source"><b>${esc(s.source_type)}</b> · <span class="ltr">${esc(s.published_at||'')}</span><br>${esc(s.statement||'')}${s.url?`<br><a href="${esc(s.url)}" target="_blank" rel="noreferrer">פתח מקור ↗</a>`:''}</div>`).join('')||'<div class="company">אין מקורות מקושרים.</div>'}
function timeline(a){return (a.date?.timeline||[]).map(t=>`<div class="time-item"><span class="date">${esc(t.date||'')}</span><span>${esc(t.text||t.date_text||'')}</span></div>`).join('')||'<div class="company">אין timeline.</div>'}
function market(a){let m=a.market||{};if(!m.available)return `<div class="notice">Market setup אינו פעיל: ${esc(m.reason||'אין מספיק מחירי PIT')}</div>`;let rs=m.returns||{};return `<div class="detail-grid"><div class="detail-box"><div class="k">Last close</div><div class="v">${esc(m.last_close?.close??'—')}</div></div><div class="detail-box"><div class="k">Vol 20D</div><div class="v">${pct(m.realized_vol_20d)}</div></div><div class="detail-box"><div class="k">T-30</div><div class="v">${pct(rs['T-30'])}</div></div></div>`}
function openEvent(id){let a=findEvent(id);if(!a)return;let w=a.date?.window||{};$('drawerContent').innerHTML=`<div class="drawer-head"><div><h2><span class="ltr">${esc(a.ticker)}</span> · ${esc(a.company||'')}</h2><p>${esc(a.program)}</p></div><button class="close" onclick="closeDrawer()">×</button></div><div class="drawer-body"><div style="display:flex;gap:7px;flex-wrap:wrap">${typeBadge(a.type)}${stateBadge(a.state?.status)}${clsBadge(a.classification?.class)}</div><div class="detail-grid"><div class="detail-box"><div class="k">Impact</div><div class="v">${score(a.impact?.score)}</div></div><div class="detail-box"><div class="k">Evidence</div><div class="v">${score(a.evidence?.score)}</div></div><div class="detail-box"><div class="k">Verification</div><div class="v">${esc(a.state?.verification_confidence)}%</div></div><div class="detail-box"><div class="k">חלון</div><div class="v ltr">${esc(w.start||'—')} → ${esc(w.end||'—')}</div></div><div class="detail-box"><div class="k">ימים</div><div class="v">${days(a)}</div></div><div class="detail-box"><div class="k">Session</div><div class="v">${esc(a.state?.event_session||'unknown')}</div></div></div><div class="notice blue-note"><b>${esc(a.evidence?.probability_label||'')}</b><br>${(a.classification?.reasons||[]).map(esc).join(' · ')}</div><div style="display:flex;gap:8px"><button class="btn primary" ${apiMode?'':'disabled'} onclick="savePaper('${esc(a.id)}')">שמור Paper Signal</button>${a.sources?.[0]?.url?`<a class="btn" href="${esc(a.sources[0].url)}" target="_blank" style="text-decoration:none">מקור ראשי ↗</a>`:''}</div><div class="section"><h4>Evidence — למה הציון נראה כך?</h4><div class="reason-list">${reasonRows(a)}</div></div><div class="section"><h4>סיכונים</h4><div class="risk-list">${risks(a)}</div></div><div class="section"><h4>Market setup</h4>${market(a)}</div><div class="section"><h4>Timeline</h4><div class="timeline">${timeline(a)}</div></div><div class="section"><h4>מקורות</h4><div class="source-list">${sources(a)}</div></div></div>`;$('backdrop').classList.add('on');$('drawer').classList.add('on');}
function closeDrawer(){$('backdrop').classList.remove('on');$('drawer').classList.remove('on')}
async function savePaper(id){if(!apiMode)return;setLoading(true);try{let r=await fetch('/api/paper',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_id:id,as_of:D.today})});let x=await r.json();if(!r.ok)throw Error(x.error||r.status);toast('Paper Signal נשמר');await load();page='paper';closeDrawer();render();}catch(e){toast('שמירת Paper נכשלה: '+e.message)}finally{setLoading(false)}}
async function refreshNow(){if(!apiMode)return;setLoading(true);toast('מריץ discovery ואימות…');try{let r=await fetch('/api/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({months:6,sec_map:true,sec_verify:true})});let x=await r.json();if(!r.ok)throw Error(x.error||r.status);toast(x.ok?'הרענון הושלם':'הרענון הסתיים עם אזהרות');await load();render();}catch(e){toast('רענון נכשל: '+e.message)}finally{setLoading(false)}}
async function load(){setLoading(true);let err=null;try{let r=await fetch('/api/radar',{cache:'no-store'});if(!r.ok)throw Error(r.status);D=await r.json();apiMode=true;}catch(e){err=e;for(const f of ['data.json','data_v2.json']){try{let r=await fetch(f,{cache:'no-store'});if(r.ok){D=await r.json();apiMode=false;break}}catch{}}}finally{setLoading(false)}if(!D)throw err||Error('No data');$('apiDot').classList.toggle('live',apiMode);$('apiLabel').textContent=apiMode?'API חי':'Snapshot סטטי';$('refreshBtn').disabled=!apiMode;}
$('globalSearch').addEventListener('input',e=>{search=e.target.value;if(page==='dash'&&search)page='radar';render();});$('refreshBtn').onclick=refreshNow;$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');$('backdrop').onclick=closeDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});
load().then(render).catch(e=>{$('main').innerHTML=`<div class="notice red-note"><b>לא ניתן לטעון נתונים.</b><br>${esc(e.message)}<br>הרץ <span class="code">mozes app</span> או <span class="code">mozes export-v3</span>.</div>`});
